version: "3"
services:
  mongo:
    container_name: mongodb
    image: mongo
    volumes:
      - ./data:/data/db
    ports: ["27017:27017"]
    environment:
      - MONGODB_DATABASE=MongoNode
  web:
    container_name: node_api
    restart: always
    build: .
    ports: ["3333:3333"]
    links:
      - mongo